version: '3.8'
services:
  app:
    build: 
      context: .
    volumes:
      - .:/Greivence-Complaint
    ports:
      - 3000:3000
    image: app:grievence
    container_name: grievence_container
    command: npm start